[tool.poetry]
name = "amino"
version = "0.1.0"
description = "A framework to build custom domain specific languages"
authors = ["Robert Roskam <raiderrobert@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
pytest-cov = "*"
ipython  = "*"
black = "*"
flake8 = "*"
py = "^1.11.0"

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 120
